apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: hello
spec:
  containers:
  - image: docker.io/library/ubuntu
    name: hello-world
    resources: {}
    command: ["/bin/sh"]
    args:
    - "-c"
    - "aaaasdf"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
