apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: docker.io/library/ubuntu
    name: hello-world
    resources: {}
    command: ["sleep"]
    args: [3600000]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
