apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: docker.io/library/ubuntu
        name: ubuntu
        resources: {}
        command: ["/bin/sh"]
        args:
        - "-c"
        - "asdfaaaaa 100000"
  
  
